apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  KEYCLOAK_USER: {{ randAlphaNum 32 | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
