apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: port5672
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: port5672
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
